"""Saves + Issue-read (M2, ADR-0002).

* DROP ``user_content_state.read_state`` — read/unread is no longer a Content property.
  user_content_state now carries ``starred`` ONLY.
* CREATE ``user_issue_state`` — the per-(reader, ISSUE) read/unread fact, REUSING the
  existing ``read_state`` Postgres ENUM (the type is NOT recreated/dropped here; it is
  shared and stays per the M2 hard constraint).

Hand-written (not autogenerated) with explicit up/down, mirroring 0001's style.

Revision ID: 0002_saves_issue_read
Revises: 0001_initial_schema
Create Date: 2026-06-09
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "0002_saves_issue_read"
down_revision = "0001_initial_schema"
branch_labels = None
depends_on = None


# A BOUND reference to the EXISTING read_state ENUM. create_type=False so the migration
# never CREATEs or DROPs the type — it is shared/reused by user_issue_state and the
# ReadState Python enum, both of which STAY.
read_state_enum = postgresql.ENUM("unread", "read", name="read_state", create_type=False)


def upgrade() -> None:
    # 1. Drop the read_state COLUMN only (the read_state TYPE stays).
    op.drop_column("user_content_state", "read_state")

    # 2. Per-(reader, ISSUE) read/unread, reusing the read_state ENUM type.
    op.create_table(
        "user_issue_state",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("issue_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "read_state",
            read_state_enum,
            server_default=sa.text("'unread'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["issue_id"], ["issues.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "issue_id", name="uq_user_issue_state_user_issue"
        ),
    )


def downgrade() -> None:
    # Exact reverse. The read_state TYPE is left untouched throughout (shared/reused).
    op.drop_table("user_issue_state")

    # Restore the dropped column. server_default backfills existing rows so NOT NULL holds.
    op.add_column(
        "user_content_state",
        sa.Column(
            "read_state",
            read_state_enum,
            server_default=sa.text("'unread'"),
            nullable=False,
        ),
    )
